
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Apr 30 19:19:27 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 11;
  public static final int LBRACKET = 13;
  public static final int CONST = 6;
  public static final int NOT_EQUAL = 34;
  public static final int GREATER = 35;
  public static final int LPAREN = 17;
  public static final int CONTINUE = 31;
  public static final int NUM_CONST = 10;
  public static final int SEMI_COMMA = 7;
  public static final int LESS = 37;
  public static final int MINUS = 24;
  public static final int RPAREN = 18;
  public static final int AND = 42;
  public static final int OR = 43;
  public static final int COMMA = 8;
  public static final int CLASS = 15;
  public static final int INC = 20;
  public static final int DIV = 27;
  public static final int LESS_EQUAL = 38;
  public static final int PLUS = 25;
  public static final int IF = 44;
  public static final int ASSIGN = 9;
  public static final int DOT = 39;
  public static final int EOF = 0;
  public static final int RETURN = 32;
  public static final int RBRACKET = 14;
  public static final int EQUAL = 33;
  public static final int GREATER_EQUAL = 36;
  public static final int NEW = 29;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 26;
  public static final int MOD = 28;
  public static final int BREAK = 30;
  public static final int IDENT = 3;
  public static final int VOID = 19;
  public static final int ELSE = 45;
  public static final int LBRACE = 4;
  public static final int READ = 22;
  public static final int WHILE = 41;
  public static final int RBRACE = 5;
  public static final int EXTENDS = 16;
  public static final int BOOL_CONST = 12;
  public static final int DEC = 21;
  public static final int DO = 40;
  public static final int PRINT = 23;
}

